### ISSUE TITLE
Can't route when using "-" in alias

### ISSUE THREAD

**Issue by ruax2891** [darmuh/LethalConstellations#1]
I've tried setting my constellations' aliases to "13-alpha", "29-beta" and such and I could not route to any constellation, though they were showing up. I had also set other aliases without dashes, but I still couldn't route. Right after removing that alias the routing started working again.
EDIT: I've also just now tested setting other aliases in the config such as "alpha,13alpha" and it isn't working, I have no idea what I'm doing wrong
My r2modman pack is `01915e0e-1eb8-f512-0e1c-5f00764a8a9e`
If you need any more info, I'm happy to help

**Comment by darmuh** [comment]
This is sort of an issue with how base-game will filter out keywords with special characters (stuff like !@-=$)

Im not sure I can get around that at the moment, I understand wanting to have the name of the constellation look more like vanilla moons with the 000- type style so maybe i'll rework the config so that you can name your constellation something and have the main keyword be something different. Currently the shortcut keywords are *additional* commands on top of the main one

**Comment by ruax2891** [comment]
Alright cool, gotcha, although I still found an issue where I couldn't route anywhere when I used multiple aliases without dashes or special characters, is there any reason for that?

**Comment by darmuh** [comment]
still looking into this, what is odd is the default groupings use the moon's danger tier levels and there doesnt seem to be an issue with keywords like "A+ Tier" or "A- Tier"

**Comment by darmuh** [comment]
Hello, I believe I've fixed this issue with version 0.2.4

I'm honestly not sure why this issue was inconsistent but I've added some extra handling for cases like 123-Abc
